class PersoanaEroare(Exception):
    pass


class EvenimentEroare(Exception):
    pass
